
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-assets-dev
  labels:
    app: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eco-assets-dev
  template:
    metadata:
      labels:
        app: eco-assets-dev
    spec:
      containers:
        - image: harbor.ynet.gov.yk.ca/yg-github/ytgov/eco-assets:v0.0.1
          name: eco-assets
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: "/home/node/app/.env.development"
              subPath: .env
              name: env-configmap-volume
      volumes:
        - name: env-configmap-volume
          configMap:
            name: eco-asset-env-dev


      restartPolicy: Always
status: {}

